language: ruby
rvm:
- 2.5.0
services:
- postgresql
script:
- bundle exec rake db:create
- bundle exec rake db:migrate
- bundle exec rake
deploy:
  provider: heroku
  app: acebook-data-thieves
  api_key:
    secure: kR+GKc0u8xwg4cVW1du2Um8ePViX1WPUqj8Hyyp7N/rqne/QsEIboA7mAgJD1Yrp0xVOtGING7vHUDTV6AhYGnhEfBrhK39qYuALeTDGS7g1vxHUbtIePJ8wHjPLUrk294f3JNv9bFL3lGQkngQLwV0lSr4GAD1Of0HWQ9f4019iA5360iQ23tNCOtBdM1GCofozIiy2MxEfgh+09G6YHnQ1rwnZLZiNQZc0bS2i6EpdAL5WnQqIQFLdIeLtDG9rVSxsgL4428XVcYPvv+B5Y9KuGvRplftsq+ulINQxa11/cqG+1FrqbLQuujdV/6lgvWfdNZGmvaPA0dtKkvO8grkXNHzfA+vqd+XNDBeDGRw8/iI6zfQjGT4s36xV0eQiSleYs0ttMhVHcCavHdbRseRihwenuq08/BSA0aFvunUtypFZxyIRdYnp7HQPijW445dmTPo2eJwES7qeMr64L6cA455HHTvTQlP0FJjkZtEKFHL+9n1dCqAlPikUS4DvIA4vnGRUrW3oqwjj5UDM7SkFdWqmNjpsDP+zTXtYG3WfiLXn4KRm2C0jtYyl9e6p9VorFyJEerwdIYCxgBKHWwOMI/SYJeGmj1jgGACPwq4QAaImfbB3MZEGCxPxSIpJb0lSLcdbmR9oQRLnK9fR7U4EzNfvv3woLCDhOIMRU8c=
  on:
    repo: carlfjones/Acebook---Data-Thieves
    branch: travis_to_heroku
  skip_cleanup: true
  run: rake db:migrate
